### PR TITLE
SDK-190 - update lib versions and rename organization

### PR DESCRIPTION
**Pull request by i-skrypnyk**

### CODE REVIEW

**Review by i-Alex — APPROVED** [review]

**Comment by i-skrypnyk** [comment]
@i-Alex moved additional bytes check here

**Review by i-Alex — APPROVED** [review]
Additional bytes commit is ok as well

**Review by paologalligit — APPROVED** [review]
LGTM

**Comment by i-Alex** [comment]
@i-skrypnyk pls, resolve the conflicts, then I will merge

**Review by i-Alex — APPROVED** [review]

**Pull request merged**
